from typing import Optional

BERUFSFELDER = [
    {
        "id": "handwerk",
        "name": "Handwerk & Technik",
        "icon": "🔧",
        "kurz": "Mit den Händen erschaffen, reparieren, bauen.",
        "beschreibung": "Hier geht es ums Tun und Machen. Du arbeitest mit Werkzeugen, Maschinen oder Materialien – und siehst am Ende, was du geleistet hast. Von Elektrotechnik über Tischlerei bis hin zu Mechatronik.",
        "beispiele": ["Elektriker/in", "Tischler/in", "Mechatroniker/in", "KFZ-Mechatroniker/in", "Maurer/in", "Feinmechaniker/in"],
    },
    {
        "id": "naturwissenschaften",
        "name": "Naturwissenschaften & Forschung",
        "icon": "🔬",
        "kurz": "Fragen stellen, forschen, verstehen.",
        "beschreibung": "Du willst wissen, warum Dinge so funktionieren, wie sie funktionieren. Experimente, Daten, Theorien – das ist dein Spielfeld. Biologie, Chemie, Physik, Mathematik.",
        "beispiele": ["Biologe/Biologin", "Chemiker/in", "Physiker/in", "Mathematiker/in", "Laborant/in"],
    },
    {
        "id": "medizin",
        "name": "Medizin & Gesundheit",
        "icon": "🏥",
        "kurz": "Menschen gesund machen und halten.",
        "beschreibung": "Du willst Krankheiten bekämpfen, Schmerzen lindern, Leben retten – oder Menschen dabei helfen, gesund zu bleiben. Ein Feld mit viel Verantwortung und echter Wirkung.",
        "beispiele": ["Arzt/Ärztin", "Zahnmedizin", "Pharmakologie", "Medizintechnik", "Rettungsdienst"],
    },
    {
        "id": "pflege",
        "name": "Pflege & Therapie",
        "icon": "🤝",
        "kurz": "Nah am Menschen, mit Herz und Kompetenz.",
        "beschreibung": "Du begleitest Menschen in schwierigen Phasen – körperlich, emotional, im Alltag. Pflege, Physiotherapie, Ergotherapie, Logopädie. Hier zählt Empathie genauso wie Fachwissen.",
        "beispiele": ["Pflegefachkraft", "Physiotherapeut/in", "Ergotherapeut/in", "Logopäd/in", "Hebamme"],
    },
    {
        "id": "psychologie",
        "name": "Psychologie & Beratung",
        "icon": "🧠",
        "kurz": "Menschen verstehen, begleiten, stärken.",
        "beschreibung": "Du interessierst dich dafür, wie Menschen denken, fühlen, handeln – und wie man ihnen helfen kann, sich weiterzuentwickeln. Psychologie, Coaching, Beratung, Therapie.",
        "beispiele": ["Psycholog/in", "Psychotherapeut/in", "Sozialberatung", "Coach", "Mediator/in"],
    },
    {
        "id": "paedagogik",
        "name": "Pädagogik & Bildung",
        "icon": "📚",
        "kurz": "Wissen weitergeben, Entwicklung begleiten.",
        "beschreibung": "Du magst es, anderen etwas beizubringen – Kindern, Jugendlichen, Erwachsenen. Schule, Kita, Weiterbildung, Hochschule oder außerschulische Bildung.",
        "beispiele": ["Lehrer/in", "Erzieher/in", "Sozialpädagog/in", "Ausbilder/in", "Hochschuldozent/in"],
    },
    {
        "id": "soziales",
        "name": "Soziales & Gemeinwesen",
        "icon": "🌍",
        "kurz": "Gesellschaft mitgestalten, Menschen unterstützen.",
        "beschreibung": "Du willst etwas bewegen – für Benachteiligte, für Gemeinschaften, für die Gesellschaft. Soziale Arbeit, Jugendhilfe, Integration, Gemeinwesenarbeit.",
        "beispiele": ["Sozialarbeiter/in", "Jugendberater/in", "Integrationshelfer/in", "Streetworker/in"],
    },
    {
        "id": "recht",
        "name": "Recht & Verwaltung",
        "icon": "⚖️",
        "kurz": "Regeln verstehen, Gerechtigkeit schaffen.",
        "beschreibung": "Du denkst strukturiert, arbeitest präzise und willst, dass Dinge gerecht und regelkonform ablaufen. Jura, öffentliche Verwaltung, Compliance, Notar.",
        "beispiele": ["Jurist/in", "Richter/in", "Verwaltungsfachangestellte/r", "Notar/in", "Rechtsanwalt/-anwältin"],
    },
    {
        "id": "wirtschaft",
        "name": "Wirtschaft & Management",
        "icon": "📊",
        "kurz": "Unternehmen führen, Strategien entwickeln.",
        "beschreibung": "Du denkst in Zahlen, Strukturen und Strategien. Du willst Unternehmen, Teams oder Projekte voranbringen. BWL, Management, Personalwesen, Unternehmensberatung.",
        "beispiele": ["Betriebswirt/in", "Manager/in", "Personalreferent/in", "Unternehmensberater/in", "Projektleiter/in"],
    },
    {
        "id": "finanzen",
        "name": "Finanzen & Steuern",
        "icon": "💰",
        "kurz": "Mit Zahlen arbeiten, Finanzen gestalten.",
        "beschreibung": "Zahlen, Bilanzen, Steuern, Investitionen – das ist deine Welt. Du arbeitest präzise, denkst analytisch und willst Finanzentscheidungen fundiert treffen.",
        "beispiele": ["Steuerberater/in", "Wirtschaftsprüfer/in", "Bankkaufleute", "Finanzberater/in", "Buchhalter/in"],
    },
    {
        "id": "it",
        "name": "IT, Software & Digitalisierung",
        "icon": "💻",
        "kurz": "Digitale Welten bauen und gestalten.",
        "beschreibung": "Du denkst in Systemen, Codes und Lösungen. Programmierung, Netzwerke, KI, Cybersecurity, Datenanalyse – die digitale Welt ist riesig und wächst weiter.",
        "beispiele": ["Softwareentwickler/in", "Data Scientist", "IT-Sicherheit", "UX-Designer/in", "Netzwerkadmin"],
    },
    {
        "id": "medien",
        "name": "Medien, Kommunikation & Marketing",
        "icon": "📢",
        "kurz": "Botschaften gestalten, Menschen erreichen.",
        "beschreibung": "Du willst kommunizieren, überzeugen, informieren oder unterhalten. Journalismus, PR, Marketing, Social Media, Content – Sprache und Bild als Werkzeug.",
        "beispiele": ["Journalist/in", "PR-Manager/in", "Content Creator", "Marketing Manager/in", "Redakteur/in"],
    },
    {
        "id": "design",
        "name": "Design, Kunst & Kreativberufe",
        "icon": "🎨",
        "kurz": "Visuell denken, Schönes erschaffen.",
        "beschreibung": "Du siehst die Welt durch eine gestalterische Brille. Grafikdesign, Produktdesign, Mode, Fotografie, Illustration, Innenarchitektur – Kreativität als Kernkompetenz.",
        "beispiele": ["Grafikdesigner/in", "Fotograf/in", "Modedesigner/in", "Innenarchitekt/in", "Illustrator/in"],
    },
    {
        "id": "sprache",
        "name": "Sprache, Literatur & Kultur",
        "icon": "✍️",
        "kurz": "Mit Worten arbeiten, Kulturen verbinden.",
        "beschreibung": "Sprache ist dein Medium. Übersetzen, Schreiben, Forschen, Vermitteln – in Verlagen, Kultureinrichtungen, internationalen Organisationen oder als freier Autor.",
        "beispiele": ["Übersetzer/in", "Autor/in", "Verlagskaufleute", "Kulturmanager/in", "Dolmetscher/in"],
    },
    {
        "id": "politik",
        "name": "Politik, Gesellschaft & Internationale Zusammenarbeit",
        "icon": "🌐",
        "kurz": "Die Welt mitgestalten.",
        "beschreibung": "Du willst Einfluss nehmen – auf politische Entscheidungen, internationale Beziehungen oder gesellschaftliche Entwicklungen. NGOs, Diplomatie, Politik, Entwicklungszusammenarbeit.",
        "beispiele": ["Politikwissenschaftler/in", "Diplomat/in", "NGO-Mitarbeit", "Entwicklungshilfe", "EU-Institutionen"],
    },
    {
        "id": "umwelt",
        "name": "Umwelt, Nachhaltigkeit & Energie",
        "icon": "🌱",
        "kurz": "Für Natur und Zukunft arbeiten.",
        "beschreibung": "Klimawandel, Energiewende, Ressourcenschonung – hier arbeitest du an den wichtigsten Themen unserer Zeit. Umwelttechnik, erneuerbare Energien, Nachhaltigkeitsmanagement.",
        "beispiele": ["Umweltingenieur/in", "Nachhaltigkeitsmanager/in", "Energieberater/in", "Ökologe/Ökologin"],
    },
    {
        "id": "natur",
        "name": "Landwirtschaft, Tiere & Natur",
        "icon": "🌾",
        "kurz": "Draußen sein, mit Tieren und Pflanzen arbeiten.",
        "beschreibung": "Erde, Tiere, Pflanzen, Wälder, Meere – du magst es, nah an der Natur zu sein. Landwirtschaft, Forstwirtschaft, Tierpflege, Veterinärmedizin.",
        "beispiele": ["Landwirt/in", "Forstwirt/in", "Tierarzt/-ärztin", "Tierpfleger/in", "Gärtner/in"],
    },
    {
        "id": "logistik",
        "name": "Logistik, Verkehr & Mobilität",
        "icon": "🚚",
        "kurz": "Dinge und Menschen in Bewegung bringen.",
        "beschreibung": "Supply Chain, Transport, Infrastruktur, Städteplanung – ohne Logistik steht die Welt still. Praktisch, systemisch, international.",
        "beispiele": ["Logistikmanager/in", "Speditionskaufleute", "Pilot/in", "Stadtplaner/in", "Bahnberufe"],
    },
    {
        "id": "gastro",
        "name": "Gastronomie, Hotellerie & Events",
        "icon": "🍽️",
        "kurz": "Menschen willkommen heißen, Erlebnisse schaffen.",
        "beschreibung": "Du liebst es, wenn Menschen sich wohlfühlen und gute Erfahrungen machen. Küche, Service, Hotelmanagement, Eventplanung – ein Feld, das Offenheit und Kreativität braucht.",
        "beispiele": ["Koch/Köchin", "Hotel-Management", "Eventmanager/in", "Restaurantleiter/in", "Sommelier/Sommelière"],
    },
    {
        "id": "sicherheit",
        "name": "Sicherheit, Rettung & Schutz",
        "icon": "🚒",
        "kurz": "Anderen in Notlagen helfen und schützen.",
        "beschreibung": "Feuerwehr, Polizei, Rettungsdienst, Militär, Bevölkerungsschutz – du willst da sein, wenn andere dich brauchen. Körperliche und mentale Stärke, Verantwortung, Teamgeist.",
        "beispiele": ["Feuerwehr", "Polizei", "Rettungssanitäter/in", "Bundesheer", "Sicherheitsdienst"],
    },
    {
        "id": "bau",
        "name": "Bau, Architektur & Immobilien",
        "icon": "🏛️",
        "kurz": "Räume und Gebäude erschaffen.",
        "beschreibung": "Vom Entwurf über die Planung bis zum fertigen Gebäude – Architektur, Ingenieurwesen, Stadtentwicklung, Immobilienwirtschaft.",
        "beispiele": ["Architekt/in", "Bauingenieur/in", "Immobilienmakler/in", "Stadtplaner/in", "Innenarchitektur"],
    },
    {
        "id": "produktion",
        "name": "Produktion, Industrie & Maschinen",
        "icon": "⚙️",
        "kurz": "Industrielle Prozesse gestalten und steuern.",
        "beschreibung": "Fertigungsplanung, Qualitätskontrolle, Maschinenbau – du willst in Produktionsprozessen arbeiten, Systeme optimieren und Dinge herstellen.",
        "beispiele": ["Maschinenbauingenieur/in", "Produktionsleiter/in", "Qualitätsmanager/in", "CNC-Fachkraft"],
    },
    {
        "id": "handel",
        "name": "Verkauf, Handel & Kundenberatung",
        "icon": "🏪",
        "kurz": "Menschen beraten, Produkte und Ideen verkaufen.",
        "beschreibung": "Du gehst gern auf Menschen zu, verstehst ihre Bedürfnisse und hilfst ihnen, das Richtige zu finden. Einzelhandel, B2B-Vertrieb, E-Commerce, Kundenservice.",
        "beispiele": ["Kaufleute im Einzelhandel", "Vertrieb B2B", "E-Commerce", "Key Account Management"],
    },
    {
        "id": "sport",
        "name": "Sport, Bewegung & Training",
        "icon": "⚽",
        "kurz": "Durch Bewegung begeistern und begleiten.",
        "beschreibung": "Sporttraining, Fitness, Physiologie, Sportmanagement oder Sportjournalismus – du willst Bewegung in dein Berufsleben bringen.",
        "beispiele": ["Sportlehrer/in", "Personal Trainer/in", "Sportmanagement", "Physiotherapeut/in mit Sportfokus"],
    },
    {
        "id": "selbststaendig",
        "name": "Selbstständige & ungewöhnliche Berufswege",
        "icon": "✨",
        "kurz": "Eigene Wege gehen, Dinge neu denken.",
        "beschreibung": "Freelancing, Gründung, Portfoliokarriere, Hybrid-Berufe – du willst nicht in klassische Schubladen passen. Hier ist Platz für alle, die sich ihren Weg selbst bauen wollen.",
        "beispiele": ["Unternehmensgründung", "Freelancer/in", "Content Creator", "Hybridberufe", "Social Entrepreneur"],
    },
]

CHARAKTEREIGENSCHAFTEN = [
    {"id": "einfuehlsam", "name": "einfühlsam", "erklaerung": "Du nimmst wahr, wie es anderen geht, und kannst dich in ihre Lage versetzen."},
    {"id": "geduldig", "name": "geduldig", "erklaerung": "Du bleibst ruhig, auch wenn etwas Zeit braucht oder nicht sofort klappt."},
    {"id": "neugierig", "name": "neugierig", "erklaerung": "Du willst wissen, wie Dinge funktionieren – du fragst, forschst, lernst gern."},
    {"id": "kreativ", "name": "kreativ", "erklaerung": "Du findest neue Ideen, denkst um die Ecke, kombinierst Dinge auf ungewöhnliche Weise."},
    {"id": "analytisch", "name": "analytisch", "erklaerung": "Du zerlegst Probleme in Teile, erkennst Muster und denkst systematisch."},
    {"id": "verantwortungsbewusst", "name": "verantwortungsbewusst", "erklaerung": "Du nimmst deine Aufgaben ernst und verlässt dich auf dich selbst."},
    {"id": "kontaktfreudig", "name": "kontaktfreudig", "erklaerung": "Du gehst gern auf andere Menschen zu – in neuen Gruppen fühlst du dich schnell wohl."},
    {"id": "selbststaendig", "name": "selbstständig", "erklaerung": "Du kannst allein arbeiten, brauchst keine ständige Anleitung von außen."},
    {"id": "strukturiert", "name": "strukturiert", "erklaerung": "Du magst Ordnung, Pläne und klare Abläufe."},
    {"id": "praktisch", "name": "praktisch veranlagt", "erklaerung": "Du packst gern an, probierst aus, machst lieber als zu planen."},
    {"id": "ausdauernd", "name": "ausdauernd", "erklaerung": "Du bleibst dran, auch wenn etwas schwierig wird oder lange dauert."},
    {"id": "mutig", "name": "mutig", "erklaerung": "Du traust dich, Neues zu wagen – auch wenn es unsicher ist."},
    {"id": "zuverlaessig", "name": "zuverlässig", "erklaerung": "Auf dich kann man sich verlassen. Du hältst, was du versprichst."},
    {"id": "hilfsbereit", "name": "hilfsbereit", "erklaerung": "Anderen zu helfen macht dir etwas aus – du tust es gern, nicht weil du musst."},
    {"id": "entscheidungsfreudig", "name": "entscheidungsfreudig", "erklaerung": "Du kannst Entscheidungen treffen, auch wenn nicht alle Infos vorhanden sind."},
    {"id": "flexibel", "name": "flexibel", "erklaerung": "Du passt dich gut an veränderte Situationen an."},
    {"id": "gewissenhaft", "name": "gewissenhaft", "erklaerung": "Du arbeitest sorgfältig und genau – Fehler möchtest du vermeiden."},
    {"id": "fuehrungsstark", "name": "führungsstark", "erklaerung": "Du übernimmst gern Verantwortung für eine Gruppe und kannst andere motivieren."},
    {"id": "lernbereit", "name": "lernbereit", "erklaerung": "Du bist offen dafür, Neues zu lernen – auch außerhalb der Schule."},
    {"id": "belastbar", "name": "belastbar", "erklaerung": "Du bleibst auch unter Druck oder in stressigen Phasen handlungsfähig."},
]

AKTIVITAETEN = [
    "Mit Kindern arbeiten",
    "Literarische Texte schreiben (z.B. Artikel, Reden, Bücher)",
    "Mit Babies arbeiten",
    "Im Bereich Social Media arbeiten",
    "Mit vielen unterschiedlichen Kulturen arbeiten",
    "Auf dem Bau arbeiten",
    "Mit Jugendlichen arbeiten",
    "Mit Literatur und Büchern arbeiten",
    "Im Bereich Informatik arbeiten",
    "Programmieren",
    "Mit Körperkontakt arbeiten",
    "Für Recht und Ordnung sorgen",
    "Medizinisch arbeiten",
    "Beim Fernsehen oder Radio arbeiten",
    "Designen (Schmuck, Medien, Produkte usw.)",
    "Mit Metall arbeiten",
    "Etwas kreativ gestalten",
    "Fotografieren oder filmen",
    "Kreativ arbeiten",
    "Mit Elektrizität arbeiten",
    "Beamter oder Beamtin sein",
    "Im Büro arbeiten",
    "Organisieren und planen",
    "Auf einer Bühne stehen",
    "Mit Kundenkontakt arbeiten",
    "Im Handwerk arbeiten",
    "Mit handwerklichem Werkzeug arbeiten",
    "Pläne entwerfen und daraus etwas bauen",
    "Mit Tieren arbeiten",
    "Kunden bedienen",
    "Menschen pflegen",
    "Körperlich aktiv sein",
    "Im Verkauf arbeiten",
    "Künstlerisch arbeiten",
    "Mit dem Computer arbeiten",
    "Mit Holz arbeiten",
    "Mit Pflanzen arbeiten",
    "Therapeutisch arbeiten",
    "Anderen etwas beibringen",
    "Psychologisch arbeiten",
    "Mit Lebensmitteln arbeiten",
    "Ein Fahrzeug führen",
    "Draußen arbeiten",
    "Menschen beraten",
    "In einem Labor arbeiten",
    "Um Kranke kümmern",
    "Technische Zeichnungen erstellen",
    "In der Forschung arbeiten",
    "Mit Zahlen und Daten arbeiten",
    "Menschen verschönern",
]

AUSSERGEWOEHNLICHE_BERUFE = [
    {"name": "Bundesheer", "icon": "🪖", "beschreibung": "Sicherheit, Technik, Auslandseinsätze, Führung – mit vielen Ausbildungs- und Karrieremöglichkeiten direkt beim österreichischen Bundesheer."},
    {"name": "Zoll", "icon": "🛃", "beschreibung": "Warenkontrollen, Ermittlungen, Grenzschutz – ein vielseitiger Beamtenberuf mit echtem Ermittlerfeeling."},
    {"name": "Polizei", "icon": "👮", "beschreibung": "Schutz, Ermittlung, Prävention – körperlich und mental anspruchsvoll, mit klarer gesellschaftlicher Wirkung."},
    {"name": "Schornsteinfeger/in", "icon": "🏠", "beschreibung": "Handwerk trifft Hightech: Brandschutz, Emissionsmessung, Energieberatung – ein Beruf mit Zukunft und Tradition."},
    {"name": "Berufstaucher/in", "icon": "🤿", "beschreibung": "Unter Wasser arbeiten: Reparaturen, Inspektionen, Bergungen – für alle, die es außergewöhnlich mögen."},
    {"name": "Lotse / Lotsin", "icon": "⚓", "beschreibung": "Riesige Schiffe sicher in den Hafen führen – ein kleines Berufsfeld mit enormer Verantwortung."},
    {"name": "Bestatter/in", "icon": "🕊️", "beschreibung": "Würdevolle Begleitung in schweren Momenten – ein unterschätzter Beruf mit viel menschlicher Tiefe."},
    {"name": "Sommelière / Sommelier", "icon": "🍷", "beschreibung": "Wein, Genuss, Gastronomie – wer Geschmack und Beratung liebt, kann daraus einen echten Beruf machen."},
    {"name": "Imker/in", "icon": "🐝", "beschreibung": "Bienen, Natur, Honig – als Nebenberuf oder Vollprofi, auch mit eigenem Produkt und Direktvermarktung."},
    {"name": "Pilot/in (Verkehr oder Militär)", "icon": "✈️", "beschreibung": "Fliegen als Beruf – anspruchsvolle Ausbildung, klare Karrierewege, internationale Einsätze."},
    {"name": "Forstwirt/in", "icon": "🌲", "beschreibung": "Draußen arbeiten, Wälder pflegen, Natur schützen – körperlich, sinnvoll und zukunftsrelevant."},
    {"name": "Goldschmied/in", "icon": "💍", "beschreibung": "Schmuck erschaffen, Erbstücke umarbeiten, mit Edelmetallen arbeiten – kreatives Handwerk mit Tiefgang."},
    {"name": "Kriminalbeamt/in (BKA, LKA)", "icon": "🔍", "beschreibung": "Ermitteln, analysieren, Täter überführen – für alle, die Krimis lieben und das echte Leben bevorzugen."},
    {"name": "Unternehmertum studieren (BWL + Gründung)", "icon": "🚀", "beschreibung": "Es gibt Studiengänge, die Unternehmertum, Innovation und Gründung ins Zentrum stellen – z.B. Entrepreneurship, Business Innovation oder Design Thinking. Wer ein Business aufbauen will, kann das auch lernen."},
    {"name": "Familienunternehmen übernehmen", "icon": "🏭", "beschreibung": "Viele Betriebe suchen Nachfolge – nicht nur in der eigenen Familie. Wer ein bestehendes Unternehmen übernimmt, startet nicht bei null, sondern baut auf echtem Fundament."},
    {"name": "KI & Prompt Engineering", "icon": "🤖", "beschreibung": "Wer versteht, wie man KI-Tools richtig einsetzt und trainiert, ist in fast jeder Branche wertvoll. Prompt Engineering, KI-Koordination und AI-Produktentwicklung sind junge Berufsfelder mit riesigem Potenzial."},
    {"name": "Startup gründen", "icon": "💡", "beschreibung": "Eine eigene Idee umsetzen, ein Problem lösen, ein Team aufbauen – Gründen kann man lernen. Inkubatoren, Acceleratoren und Förderprogramme gibt es auch für Berufseinsteiger ohne Kapital."},
    {"name": "Arbeiten im Ausland", "icon": "🌍", "beschreibung": "In einem anderen Land arbeiten, eine Sprache wirklich lernen, eine andere Kultur von innen erleben – das verändert. Ob Au-pair, Work & Travel, internationale Ausbildung oder Lehre: die Welt ist größer als Österreich."},
    {"name": "Content Creator / Creator Economy", "icon": "🎥", "beschreibung": "YouTube, TikTok, Instagram, Podcast – wer eine echte Meinung und ein Thema hat, kann daraus ein Business machen. Das ist kein Glück, sondern ein Handwerk, das man lernen kann."},
    {"name": "Social Entrepreneurship", "icon": "🌱", "beschreibung": "Ein Unternehmen gründen, das nicht nur Geld verdient, sondern ein gesellschaftliches Problem löst. Soziale Innovation, NGO-Management und Impact Business sind echte Berufsfelder mit Wachstum."},
    {"name": "Parfumeur/in", "icon": "🌸", "beschreibung": "Düfte entwickeln, Rohstoffe kombinieren, Emotionen in Flaschen fassen – ein seltener Beruf mit langer Ausbildung, der Kreativität und Wissenschaft vereint. Parfümerien, Kosmetikkonzerne oder Selbstständigkeit."},
    {"name": "Koch/Köchin (bis zur Sterneküche)", "icon": "👨‍🍳", "beschreibung": "Kochen kann Handwerk sein – oder Kunst. Vom Ausbildungsbetrieb bis zur Sterneküche, vom eigenen Catering bis zur Food-Content-Creation: Wer mit Essen umgehen kann, hat viele Wege."},
    {"name": "Tänzer/in & Tanzpädagog/in", "icon": "💃", "beschreibung": "Tanz als Beruf – ob als Performer, Choreograf/in oder in der Pädagogik. Tanzschulen, Theater, Kreativprojekte, therapeutischer Tanz: Körper und Ausdruck als Werkzeug."},
    {"name": "Musiker/in & Musikpädagog/in", "icon": "🎵", "beschreibung": "Musik als Beruf ist mehr als die große Bühne: Unterrichten, komponieren, produzieren, Session-Musiker, Musiktherapie – wer Musik liebt, findet viele realistische Wege."},
]

STEPS_ORDER = [
    "start",
    "fakten",
    "reflexion",
    "charakter",
    "werte",
    "energie",
    "berufsfelder",
    "vergleich",
    "laden",
    "ergebnis",
    "favoriten",
    "pdf",
]

WERTE_AUKTION = [
    {"id": "sinn",          "name": "Sinn / etwas Bedeutsames tun"},
    {"id": "geld",          "name": "Geld / finanzielle Sicherheit"},
    {"id": "freiheit",      "name": "Freiheit / Selbstbestimmung"},
    {"id": "familie",       "name": "Familie / enge Beziehungen"},
    {"id": "abenteuer",     "name": "Abenteuer / neue Erfahrungen"},
    {"id": "sicherheit",    "name": "Sicherheit / Stabilität"},
    {"id": "anerkennung",   "name": "Anerkennung / sichtbar sein"},
    {"id": "kreativitaet",  "name": "Kreativität / etwas erschaffen"},
    {"id": "lernen",        "name": "Lernen / dich entwickeln"},
    {"id": "helfen",        "name": "Anderen helfen / dazugehören"},
]

ENERGIE_STUNDEN = list(range(6, 23))

STEP_NAMES = {
    "start": "Start",
    "fakten": "Deine Situation",
    "video": "Video",
    "reflexion": "Selbstreflexion",
    "charakter": "Charakterprofil",
    "berufsfelder": "Berufsfelder",
    "vergleich": "Vergleich",
    "laden": "Auswertung",
    "ergebnis": "Dein Ergebnis",
    "favoriten": "Favoriten",
    "pdf": "Dein goldener Tropfen",
}


def get_step_number(step: str) -> int:
    try:
        return STEPS_ORDER.index(step)
    except ValueError:
        return 0


def get_progress_percent(step: str) -> int:
    idx = get_step_number(step)
    return int((idx / (len(STEPS_ORDER) - 1)) * 100)


def get_berufsfeld_by_id(bid: str) -> Optional[dict]:
    for b in BERUFSFELDER:
        if b["id"] == bid:
            return b
    return None
